# Generated by Django 3.1.1 on 2020-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0003_auto_20201104_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shops', models.BooleanField(default=False, verbose_name='shops')),
                ('cafes', models.BooleanField(default=False, verbose_name='cafes')),
                ('bars', models.BooleanField(default=False, verbose_name='bars')),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='bars',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='cafes',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='shops',
        ),
    ]
