# Generated by Django 3.1.1 on 2020-11-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0004_auto_20201113_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='measurement',
            name='bars',
            field=models.BooleanField(default=False, verbose_name='bars'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='cafes',
            field=models.BooleanField(default=False, verbose_name='cafes'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='shops',
            field=models.BooleanField(default=False, verbose_name='shops'),
        ),
    ]
