# Generated by Django 3.1.1 on 2020-11-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0005_auto_20201120_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='bakery',
            field=models.BooleanField(default=False, verbose_name='bakery'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='beauty',
            field=models.BooleanField(default=False, verbose_name='beauty'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='bicycle_rental',
            field=models.BooleanField(default=False, verbose_name='bicycle_rental'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='bureau_de_change',
            field=models.BooleanField(default=False, verbose_name='bureau_de_change'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='clock',
            field=models.BooleanField(default=False, verbose_name='clock'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='clothes',
            field=models.BooleanField(default=False, verbose_name='clothes'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='fast_food',
            field=models.BooleanField(default=False, verbose_name='fast_food'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='florist',
            field=models.BooleanField(default=False, verbose_name='florist'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='fountain',
            field=models.BooleanField(default=False, verbose_name='fountain'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='historic',
            field=models.BooleanField(default=False, verbose_name='historic'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ice_cream',
            field=models.BooleanField(default=False, verbose_name='ice_cream'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='kiosk',
            field=models.BooleanField(default=False, verbose_name='kiosk'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pharmacy',
            field=models.BooleanField(default=False, verbose_name='pharmacy'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='supermamrket',
            field=models.BooleanField(default=False, verbose_name='supermamrket'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='tree',
            field=models.BooleanField(default=False, verbose_name='tree'),
        ),
    ]
