# Generated by Django 3.1.1 on 2020-11-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webexample', '0006_auto_20201125_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='shops',
        ),
    ]
